[profile.default]
src = "src"
out = "out"
solc = "0.8.18"
libs = ["lib"]

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
tes = "${TESCHAIN_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
